// Generated by CoffeeScript 1.9.3
String.prototype.camelize = function() {
  return this.replace(/(^|\-|\_)(\w)/g, function(a, b, c) {
    return c.toUpperCase();
  });
};

String.prototype.snakize = function() {
  var res;
  res = this.replace(/[A-Z]/g, function(s) {
    return "_" + s.charAt(0).toLowerCase();
  });
  return res.substring((res.substring(0, 1) === '_' ? 1 : 0));
};

$().ready(function() {
  $('#camelize').on('click', function() {
    return $('#after').val($('#before').val().camelize());
  });
  $('#snakize').on('click', function() {
    return $('#after').val($('#before').val().snakize());
  });
  return $('#before, #after').on('click', function() {
    return $(this).select();
  });
});
