// Generated by CoffeeScript 1.12.7
var mt_rand;

window.TOOLS = ['json_viewer', 'case_converter', 'password_generator', 'qrcode', 'anagram', 'roulette', 'random_picker', 'telopper', 'time_converter'];

$().ready(function() {
  var htmls, j, len, ref, toolName;
  htmls = [];
  ref = window.TOOLS;
  for (j = 0, len = ref.length; j < len; j++) {
    toolName = ref[j];
    htmls.push('<a href="./' + toolName + '.html"><img width="32" height="32" src="favicon/' + toolName + '.ico"></a>');
  }
  htmls.push('<a href="https://github.com/rev84/tools" target="_blank">GitHub</a>');
  return $('#menu').html(htmls.join(' / '));
});

mt_rand = function(min, max) {
  Math.round();
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

Array.prototype.shuffle = function() {
  var i, n, ref;
  n = this.length;
  while (n) {
    n--;
    i = mt_rand(0, n);
    ref = [this[n], this[i]], this[i] = ref[0], this[n] = ref[1];
  }
  return this;
};

Array.prototype.in_array = function(value) {
  var j, len, ref, v;
  ref = this;
  for (j = 0, len = ref.length; j < len; j++) {
    v = ref[j];
    if (v === value) {
      return true;
    }
  }
  return false;
};

Array.prototype.copy = function() {
  var j, k, len, len1, ref, res, res2, v, v2;
  res = [];
  ref = this;
  for (j = 0, len = ref.length; j < len; j++) {
    v = ref[j];
    res2 = [];
    for (k = 0, len1 = v.length; k < len1; k++) {
      v2 = v[k];
      res2.push(v2);
    }
    res.push(res2);
  }
  return res;
};
