// Generated by CoffeeScript 1.9.3
var reset;

reset = function() {
  $('#message').html('');
  $('#compressed').removeClass('error');
  $('#ordered').removeClass('error');
};

$().ready(function() {
  $('#compressize').on('click', function() {
    var e, json, jsonArray, jsonStr;
    reset();
    json = $('#ordered').val();
    try {
      jsonArray = JSON.parse(json);
    } catch (_error) {
      e = _error;
      $('#message').html('JSONが不正です。');
      $('#ordered').addClass('error');
      return false;
    }
    jsonStr = JSON.stringify(jsonArray, null, 0);
    $('#compressed').val(jsonStr);
  });
  $('#orderize').on('click', function() {
    var e, json, jsonArray, jsonStr;
    reset();
    json = $('#compressed').val();
    try {
      jsonArray = JSON.parse(json);
    } catch (_error) {
      e = _error;
      $('#message').html('JSONが不正です。');
      $('#compressed').addClass('error');
      return false;
    }
    jsonStr = JSON.stringify(jsonArray, null, 4);
    $('#ordered').val(jsonStr);
  });
  $('#selectCompressed').on('click', function() {
    $('#compressed').select();
  });
  $('#selectOrdered').on('click', function() {
    $('#ordered').select();
  });
});
