// Generated by CoffeeScript 1.10.0
$().ready(function() {
  return $('#convert').on('click', function() {
    $('#qrcode').html('');
    return $('#qrcode').qrcode({
      size: 200,
      color: '#000000',
      text: $('#url').val()
    });
  });
});
