// Generated by CoffeeScript 1.10.0
$().ready(function() {
  $('#url').on('click', function() {
    return $(this).select();
  });
  return $('#convert').on('click', function() {
    return $('#qrcode').html('').qrcode({
      size: 200,
      color: '#000000',
      text: $('#url').val()
    }).off('click').on('click', function() {
      return window.open($('#url').val());
    });
  });
});
