// Generated by CoffeeScript 1.12.7
$().ready(function() {
  return $('#pick').on('click', function() {
    var i, isUnique, items, j, k, l, len, ref, ref1, ref2, res, times, val;
    times = Number($('#times').val());
    isUnique = $('#unique').prop('checked');
    items = [];
    ref = $('#items').val().replace(/(\r|\n|\r\n)/, "\n").split("\n");
    for (j = 0, len = ref.length; j < len; j++) {
      val = ref[j];
      if (val !== '') {
        items.push(val);
      }
    }
    items.shuffle();
    res = [];
    if (isUnique) {
      for (i = k = 0, ref1 = times; 0 <= ref1 ? k < ref1 : k > ref1; i = 0 <= ref1 ? ++k : --k) {
        if (items.length > 0) {
          res.push(items.pop());
        }
      }
    } else {
      for (i = l = 0, ref2 = times; 0 <= ref2 ? l < ref2 : l > ref2; i = 0 <= ref2 ? ++l : --l) {
        res.push(items[mt_rand(0, items.length - 1)]);
      }
    }
    return $('#result').val(res.join("\n"));
  });
});
