// Generated by CoffeeScript 2.5.1
var MAX_LOOP_COUNT, clipboradCopy, replace;

MAX_LOOP_COUNT = 1000 * 1000;

window.GLOBAL = {
  CLIPBOARD: null
};

$().ready(function() {
  $('#replace').on('click', replace);
  return $('#copy').on('click', clipboradCopy);
});

replace = function() {
  var count, end, loop_count, needle, pace, res, start, template;
  needle = $('#needle').val();
  start = Number($('#start').val());
  end = Number($('#end').val());
  pace = Number($('#pace').val());
  template = $('#template').val();
  if (isNaN(start)) {
    return alert('開始番号が異常です');
  }
  if (isNaN(end)) {
    return alert('終了番号が異常です');
  }
  if (isNaN(pace) || pace === 0) {
    return alert('番号の増加量が異常です');
  }
  if (start > end) {
    return alert('開始番号＞終了番号になっています');
  }
  loop_count = Math.abs((end - start) / pace);
  if (isNaN(loop_count) || loop_count > MAX_LOOP_COUNT) {
    return alert('' + MAX_LOOP_COUNT.toLocaleString() + '回を超えるループになっています');
  }
  res = '';
  count = start;
  while (true) {
    res += template.replaceAll(needle, count.toString());
    count += pace;
    if ((pace < 0 && count < end) || (pace > 0 && count > end)) {
      break;
    }
  }
  return $('#result').html(res);
};

clipboradCopy = function() {
  return navigator.clipboard.writeText($('#result').html());
};
