// Generated by CoffeeScript 2.5.1
var MAX_LOOP_COUNT, calcableConfig, clipboradCopy, replace;

MAX_LOOP_COUNT = 1000 * 1000;

window.GLOBAL = {
  CLIPBOARD: null
};

$().ready(function() {
  $('#replace').on('click', replace);
  $('#copy').on('click', clipboradCopy);
  return $('#calcable').on('change', calcableConfig);
});

calcableConfig = function() {
  if ($('#calcable').prop('checked')) {
    return $('.calcable_config').removeClass('no_display');
  } else {
    return $('.calcable_config').addClass('no_display');
  }
};

replace = function() {
  var calcable, count, end, kakko_end, kakko_start, loop_count, needle, pace, reg, replaceString, res, start, template;
  needle = $('#needle').val();
  start = Number($('#start').val());
  end = Number($('#end').val());
  pace = Number($('#pace').val());
  template = $('#template').val();
  calcable = $('#calcable').prop('checked');
  kakko_start = $('#kakko_start').val();
  kakko_end = $('#kakko_end').val();
  if (isNaN(start)) {
    return alert('開始番号が異常です');
  }
  if (isNaN(end)) {
    return alert('終了番号が異常です');
  }
  if (isNaN(pace) || pace === 0) {
    return alert('番号の増加量が異常です');
  }
  if (start > end) {
    return alert('開始番号＞終了番号になっています');
  }
  loop_count = Math.abs((end - start) / pace);
  if (isNaN(loop_count) || loop_count > MAX_LOOP_COUNT) {
    return alert('' + MAX_LOOP_COUNT.toLocaleString() + '回を超えるループになっています');
  }
  res = '';
  count = start;
  while (true) {
    if (calcable) {
      reg = new RegExp('' + kakko_start + '([^' + kakko_end + ']*)' + kakko_end, 'g');
      replaceString = function(str, p) {
        return eval(p.replaceAll(needle, count));
      };
      res += template.replaceAll(reg, replaceString);
    } else {
      res += template.replaceAll(needle, count.toString());
    }
    count += pace;
    if ((pace < 0 && count < end) || (pace > 0 && count > end)) {
      break;
    }
  }
  return $('#result').html(res);
};

clipboradCopy = function() {
  return navigator.clipboard.writeText($('#result').html());
};
